Repository OPM/opm-grid, pull requests merged in 2025-08, with the labels that each got.

#904 Revert entity test with geometry
  tests/cpgrid/entity_test.cpp
Labels: manual:irrelevant

#907 Remove unnecessary friend declarations
  opm/grid/cpgrid/CpGridData.hpp
Labels: manual:irrelevant

#908 Group lgr tests
  CMakeLists_files.cmake
  tests/cpgrid/lgr/LgrChecks.hpp
  tests/cpgrid/lgr/adapt_cpgrid_test.cpp
  tests/cpgrid/lgr/addLgrsOnDistributedGrid_test.cpp
  tests/cpgrid/lgr/avoidNNCinLGRsCpGrid_test.cpp
  tests/cpgrid/lgr/avoidNNCinLGRs_test.cpp
  tests/cpgrid/lgr/communicate_distributed_grid_with_lgrs_test.cpp
  tests/cpgrid/lgr/cuboidShape_test.cpp
  tests/cpgrid/lgr/distribute_level_zero_from_grid_with_lgrs_and_wells_test.cpp
  tests/cpgrid/lgr/distribute_level_zero_from_grid_with_lgrs_test.cpp
  tests/cpgrid/lgr/global_refine_test.cpp
  tests/cpgrid/lgr/grid_global_id_set_test.cpp
  tests/cpgrid/lgr/grid_lgr_test.cpp
  tests/cpgrid/lgr/lgrIJK_test.cpp
  tests/cpgrid/lgr/lgr_cartesian_idx_test.cpp
  tests/cpgrid/lgr/lgr_cell_id_sync_test.cpp
  tests/cpgrid/lgr/lgr_coord_zcorn_test.cpp
  tests/cpgrid/lgr/lgr_with_inactive_parent_cells_test.cpp
  tests/cpgrid/lgr/logicalCartesianSize_and_refinement_test.cpp
  tests/cpgrid/lgr/lookUpCellCentroid_cpgrid_test.cpp
  tests/cpgrid/lgr/lookupdataCpGrid_test.cpp
  tests/cpgrid/lgr/replace_lgr1_corner_idx_by_lgr2_corner_idx_test.cpp
  tests/cpgrid/lgr/replace_lgr1_face_idx_by_lgr2_face_idx_test.cpp
  tests/cpgrid/lgr/save_lgr_coord_zcorn_test.cpp
Labels: manual:irrelevant

#913 Fix bug in faceCell().
  opm/grid/CpGrid.hpp
  opm/grid/cpgrid/CpGrid.cpp
Labels: manual:bugfix

#887 Test (Level)CartesianIndexMapper for CpGrid with LGRs
  CMakeLists.txt
  CMakeLists_files.cmake
  opm/grid/cpgrid/CpGrid.cpp
  opm/grid/cpgrid/CpGridData.hpp
  opm/grid/cpgrid/LevelCartesianIndexMapper.hpp
  tests/cpgrid/lgr/LgrChecks.hpp
  tests/cpgrid/lgr/level_and_grid_cartesianIndexMappers_test.cpp
  tests/cpgrid/lgr/lgr_with_inactive_parent_cells_test.cpp
  tests/cpgrid/lgr/logicalCartesianSize_and_refinement_test.cpp
Labels: manual:irrelevant

#912 Refactor and rename grid_lgr_test.cpp
  CMakeLists_files.cmake
  opm/grid/CpGrid.hpp
  opm/grid/cpgrid/CpGrid.cpp
  opm/grid/cpgrid/CpGridData.hpp
  tests/cpgrid/lgr/addLgrs_in_allActiveCartesianGrid_test.cpp
  tests/cpgrid/lgr/grid_lgr_test.cpp
Labels: manual:irrelevant

#906 Fix empty pointMapping_ when synchrCellIds in adapt() calls
  opm/grid/cpgrid/CpGrid.cpp
Labels: manual:irrelevant

#814 Add Support for Edge Conformal Corner-Point Grid Processing
  CMakeLists_files.cmake
  opm/grid/CpGrid.hpp
  opm/grid/GridManager.cpp
  opm/grid/GridManager.hpp
  opm/grid/cornerpoint_grid.c
  opm/grid/cornerpoint_grid.h
  opm/grid/cpgpreprocess/facetopology.c
  opm/grid/cpgpreprocess/facetopology.h
  opm/grid/cpgpreprocess/make_edge_conformal.cpp
  opm/grid/cpgpreprocess/make_edge_conformal.hpp
  opm/grid/cpgpreprocess/preprocess.c
  opm/grid/cpgpreprocess/preprocess.h
  opm/grid/cpgrid/CpGrid.cpp
  opm/grid/cpgrid/CpGridData.hpp
  opm/grid/cpgrid/processEclipseFormat.cpp
  opm/grid/polyhedralgrid/grid.hh
  tests/test_column_extract.cpp
  tests/test_process_grdecl.cpp
  tests/test_ug.cpp
Labels: manual:new-feature

#918 Janitoring: quell some SCA warnings
  opm/grid/CpGrid.hpp
  opm/grid/common/GridPartitioning.cpp
  opm/grid/cpgpreprocess/make_edge_conformal.cpp
  opm/grid/cpgrid/CpGrid.cpp
  opm/grid/cpgrid/CpGridData.hpp
  opm/grid/cpgrid/ElementMarkHandle.hpp
  opm/grid/cpgrid/Geometry.hpp
  tests/cpgrid/lgr/communicate_distributed_grid_with_lgrs_test.cpp
  tests/cpgrid/lgr/lgr_with_inactive_parent_cells_test.cpp
  tests/cpgrid/lgr/save_lgr_coord_zcorn_test.cpp
Labels: manual:irrelevant

#909 Move LGR helpers out of CpGrid
  CMakeLists_files.cmake
  opm/grid/CpGrid.hpp
  opm/grid/cpgrid/CpGrid.cpp
  opm/grid/cpgrid/CpGridData.cpp
  opm/grid/cpgrid/CpGridData.hpp
  opm/grid/cpgrid/Indexsets.hpp
  opm/grid/cpgrid/LgrHelpers.cpp
  opm/grid/cpgrid/LgrHelpers.hpp
  tests/cpgrid/lgr/adapt_cpgrid_test.cpp
  tests/cpgrid/lgr/addLgrsOnDistributedGrid_test.cpp
  tests/cpgrid/lgr/addLgrs_if_non_nnc_in_lgrs_test.cpp
  tests/cpgrid/lgr/avoidNNCinLGRsCpGrid_test.cpp
  tests/cpgrid/lgr/avoidNNCinLGRs_test.cpp
  tests/cpgrid/lgr/cuboidShape_test.cpp
  tests/cpgrid/lgr/distribute_level_zero_from_grid_with_lgrs_and_wells_test.cpp
  tests/cpgrid/lgr/distribute_level_zero_from_grid_with_lgrs_test.cpp
  tests/cpgrid/lgr/global_refine_test.cpp
  tests/cpgrid/lgr/grid_global_id_set_test.cpp
  tests/cpgrid/lgr/lgrIJK_test.cpp
  tests/cpgrid/lgr/lgr_cartesian_idx_test.cpp
  tests/cpgrid/lgr/lgr_cell_id_sync_test.cpp
  tests/cpgrid/lgr/lgr_coord_zcorn_test.cpp
  tests/cpgrid/lgr/logicalCartesianSize_and_refinement_test.cpp
  tests/cpgrid/lgr/lookUpCellCentroid_cpgrid_test.cpp
  tests/cpgrid/lgr/lookupdataCpGrid_test.cpp
  tests/cpgrid/lgr/replace_lgr1_corner_idx_by_lgr2_corner_idx_test.cpp
  tests/cpgrid/lgr/replace_lgr1_face_idx_by_lgr2_face_idx_test.cpp
  tests/cpgrid/lgr/save_lgr_coord_zcorn_test.cpp
Labels: manual:irrelevant
